### PR TITLE
Feature/map in posts

### PR DESCRIPTION
**Pull request by Fernan2**
Before:

```

---
date: 2016-10-18 19:00
title: "Introducción a Open Data"

---
date: 2016-09-27 19:00
title: "Breaking the rules"
```

Now:

```

---
date: 2016-10-18 19:00
title: "Introducción a Open Data"
where: Flywire

---
date: 2016-09-27 19:00
title: "Breaking the rules"
where: GeeksHubs
```

That shows the appropriate map & logo on the post page. Also will keep synched the homepage.

### CODE REVIEW

**Comment by esebastian** [comment]
Homepage build fails if there's no `where` value. Post page works ok.

I don't dislike the `where` term, but perhaps `location` or `venue` would be more suitable. Also I wouldn't add the venue name in the map heading, I like the simple 'Localización' one. What do you people think?

**Comment by d2bit** [comment]
Agree! `location` seems better name.
I've also noticed that the map have different sizes in each _partial_

**Comment by Fernan2** [comment]
Ok to renaming to `location`

About map sizes, I just took the last ones we used, but I'll aply the parameters of the current iframe to the GeeksHubs map.

About the homepage, I did purposely. While adding location to old posts wasn't worth, I think that new ones should always have it. But if you find it unsafe... what should be the fallback behavior? An empty space to make it obvious? Flywire (as it's the fallback for post page)?

I'd also like more opinions about the heading `Localización: Flywire` instead of the old `Localización`

**Comment by vibaiher** [comment]
👍 

About the heading... I don't mind. I think `Localización` it's good enough since there is a map that already has the name of the location, but I don't mind.

**Comment by esebastian** [comment]
Do we keep the `Localización` header then?

**Comment by Fernan2** [comment]
It's removed; the truth is that the point of this PR was adding the map, not other stuff.

**Pull request merged**
